#!/bin/bash

# Script to generate APM prompt primitives from the prompts/ collection.
#
# APM (Agent Package Manager) producers ship installable primitives under
# .apm/. See https://microsoft.github.io/apm/producer/author-primitives/prompts/
#
# The browsable prompts/ collection is the single source of truth. This script
# transforms each prompts/<category>/<name>.md file into an APM prompt primitive
# at .apm/prompts/<category>-<name>.prompt.md so consumers can install them with
#   apm install DevSecNinja/gpt-prompts
#
# Generated files are deterministic and committed to the repository, mirroring
# how INDEX.md and README.md are generated by scripts/generate-index.sh.

set -euo pipefail

# Enable globstar for ** matching and nullglob so empty globs disappear.
shopt -s globstar nullglob

OUTPUT_DIR=".apm/prompts"

echo "🤖 Generating APM prompt primitives..."

# Start from a clean output directory so removed prompts don't leave stale files.
rm -rf "$OUTPUT_DIR"
mkdir -p "$OUTPUT_DIR"

# Extract the title (first "# " heading) from a prompt file.
get_title() {
  grep -m 1 "^# " "$1" | sed 's/^# //'
}

# Extract the description (first non-empty line under "## Description").
get_description() {
  awk '
    /^## Description$/ { in_desc=1; next }
    /^## / { in_desc=0 }
    in_desc && NF > 0 { print; exit }
  ' "$1" | sed 's/^[[:space:]]*//'
}

# Extract the prompt body: the contents of the first fenced code block that
# follows the "## Prompt" heading.
get_prompt_body() {
  awk '
    /^## Prompt$/ { in_section=1; next }
    in_section && /^```/ {
      if (in_fence) { exit }
      in_fence=1; next
    }
    in_section && in_fence { print }
  ' "$1"
}

count=0

for prompt_file in prompts/**/*.md; do
  [ -f "$prompt_file" ] || continue

  category=$(basename "$(dirname "$prompt_file")")
  name=$(basename "$prompt_file" .md)
  title=$(get_title "$prompt_file")
  description=$(get_description "$prompt_file")
  body=$(get_prompt_body "$prompt_file")

  if [ -z "$body" ]; then
    echo "⚠️  Skipping $prompt_file: no '## Prompt' code block found"
    continue
  fi

  output_file="${OUTPUT_DIR}/${category}-${name}.prompt.md"

  # Emit the description as a double-quoted YAML scalar so colons, quotes and
  # other special characters in the source description stay valid.
  escaped_description=${description//\\/\\\\}
  escaped_description=${escaped_description//\"/\\\"}

  {
    echo "---"
    echo "description: \"${escaped_description}\""
    echo "---"
    echo ""
    echo "# ${title}"
    echo ""
    echo "${body}"
  } > "$output_file"

  count=$((count + 1))
  echo "  ✓ ${output_file}"
done

echo "✅ Generated ${count} APM prompt primitive(s) in ${OUTPUT_DIR}/"
